import Nav from '@/components/Nav';
const Privacy = () => {
  return (
    <>
      <Nav />
      <section className="p-4 md:max-w-md mx-auto">
        <h1 className="font-bold text-xl text-center mb-2 text-primary">
          Privacy Policy Page
        </h1>
        <p className="font-bold mb-2">Last updated: April 05, 2024</p>
        <p className="mb-2">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="mb-2">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the{' '}
          <a
            href="https://www.termsfeed.com/privacy-policy-generator/"
            target="_blank"
          >
            Privacy Policy Generator.
          </a>
        </p>
        <h3 className="mb-2 font-bold text-lg">
          Interpretation and Definitions
        </h3>
        <h4 className="mb-2 text-lg">Interpretation</h4>
        <p className="mb-2">
          The words of which the initial letter is capitalised have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h4 className="mb-2 font-bold text-lg">Definitions</h4>
        <p className="mb-2 text-lg">For the purposes of this Privacy Policy:</p>
        <ul className="mb-2 list-inside list-disc">
          <li className="mb-2">
            <b>Account</b> means a unique account created for You to access our
            Service or parts of our Service.
          </li>
          <li className="mb-2">
            <b>Affiliate</b> means an entity that controls, is controlled by or
            is under common control with a party, where &quot;control&quot;
            means ownership of 50% or more of the shares, equity interest or
            other securities entitled to vote for election of directors or other
            managing authority.
          </li>
          <li className="mb-2">
            <b>Company</b> {'('}referred to as either &quot;the Company&quot;,
            &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement
            {')'} refers to inviami.com.
          </li>
          <li className="mb-2">
            <b>Cookies</b> are small files that are placed on Your computer,
            mobile device or any other device by a website, containing the
            details of Your browsing history on that website among its many
            uses.
          </li>
          <li className="mb-2">
            <b>Country</b> refers to: United Kingdom.
          </li>
          <li className="mb-2">
            <b>Device</b> means any device that can access the Service such as a
            computer, a cellphone or a digital tablet.
          </li>
          <li className="mb-2">
            <b>Personal Data</b> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li className="mb-2">
            <b>Service</b> refers to the Website.
          </li>
          <li className="mb-2">
            <b>Service Provider</b> means any natural or legal person who
            processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>
          <li className="mb-2">
            <b>Usage Data</b> refers to data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself {'('}for example, the duration of a page visit
            {')'}.
          </li>
          <li className="mb-2">
            <b>Website</b> refers to inviami, accessible from inviami.com.
          </li>
          <li className="mb-2">
            <b>You</b> means the individual accessing or using the Service, or
            the company, or other legal entity on behalf of which such
            individual is accessing or using the Service, as applicable.
          </li>
          <li className="mb-2">
            <b>Event</b> refers to the event created by You which results in a
            public web page that displays input data from the user/You.
          </li>
          <li className="mb-2">
            <b>Attendee</b> refers to users that have been invited to the event
            by the user/You and who submit their RSVP.
          </li>
        </ul>
        <h3 className="mb-2 mt-4 font-bold text-lg">
          Collecting and Using Your Personal Data
        </h3>
        <h4 className="mb-2">Types of Data Collected</h4>
        <h5 className="mb-2">Personal Data</h5>
        <p className="mb-2">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>

        <ul className="mb-2 list-inside list-disc">
          <li className="mb-2">First name and last name</li>
          <li className="mb-2">
            Address, State, Province, ZIP/Postal code, City of your organised
            Event
          </li>
          <li className="mb-2">
            Event title that may contain personal data such as Your Full Name
          </li>
          <li className="mb-2">Event notes that may contain personal data</li>
          <li className="mb-2">
            Event schedule that may contain personal data
          </li>
          <li className="mb-2">Event Attendees&apos; names</li>
          <li className="mb-2">
            Event Attendees&apos; notes that may contain personal data
          </li>
        </ul>
        <h3 className="mb-2 mt-4 font-bold text-lg">
          Tracking Technologies and Cookies
        </h3>
        <p className="mb-2">
          We use a similar technology to Cookies called Session Storage on the
          admin page.
        </p>
        <h3 className="mb-2 font-bold">Session storage</h3>

        <p className="mb-2">
          We use session storage to store the current user session. This is used
          to keep the user logged in when navigating on the admin pages.
        </p>
        <p className="mb-2">
          Admin pages are defined as the pages that are only accessible by the
          user/You. These pages are used to check the list of Attendees by /You.
          The endpoint for admin pages are /admin. For example,
          https://inviami.com/Your-event-title<b>/admin</b>.
        </p>
        <p className="mb-2">
          Session Cookies are deleted as soon as You close Your web browser or
          web browser tab.
        </p>
        <p className="mb-2">
          The session storage is optional and can be disabled by the user.
        </p>
        <p className="mb-2">
          The session storage helps authenticate users on the admin page. If
          this is disabled the service can still be provided, however, the user
          must log in everytime the page is refreshed.
        </p>
        <h3 className="mb-2 font-bold">Use of Your Personal Data</h3>
        <p className="mb-2">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="mb-2 list-inside list-disc">
          <li className="mb-2">
            <b>To provide and maintain our Service</b>, including to monitor the
            usage of our Service.
          </li>
          <li className="mb-2">
            <b>To manage Your Account:</b> to manage Your registration as a user
            of the Service. The Personal Data You provide can give You access to
            different functionalities of the Service that are available to You
            as a registered user.
          </li>
          <li className="mb-2">
            <b>For the performance of a contract:</b> the development,
            compliance and undertaking of the purchase contract for the
            products, items or services You have purchased or of any other
            contract with Us through the Service.
          </li>
          <li className="mb-2">
            <b>To contact You:</b> To contact You on Etsy messaging service
            regarding updates or informative communications related to the
            functionalities, products or contracted services, including the
            security updates, when necessary or reasonable for their
            implementation.
          </li>
          <li className="mb-2">
            <b>To manage Your requests:</b> To attend and manage Your requests
            to Us.
          </li>
          <li className="mb-2">
            <b>For business transfers:</b> We may use Your information to
            evaluate or conduct a merger, divestiture, restructuring,
            reorganization, dissolution, or other sale or transfer of some or
            all of Our assets, whether as a going concern or as part of
            bankruptcy, liquidation, or similar proceeding, in which Personal
            Data held by Us about our Service users is among the assets
            transferred.
          </li>
          <li className="mb-2">
            <b>For other purposes:</b> We may use Your information for other
            purposes, such as data analysis, identifying usage trends,
            determining the effectiveness of our promotional campaigns and to
            evaluate and improve our Service, products, services, marketing and
            your experience.
          </li>
          <li className="mb-2">
            <b>To verify your purchase: </b> In our service, where anyone can
            create an event, keeping purchases genuine is key. To do this, we
            check the Full Name You provide during onboarding against Your Etsy
            Full Name. This helps us maintain trust in our platform and ensures
            that transactions run smoothly.
          </li>
        </ul>
        <h3 className="mb-2">
          We may share Your personal information in the following situations:{' '}
        </h3>

        <ul className="mb-2 list-inside list-disc">
          <li className="mb-2">
            <b>With Service Providers:</b> We may share Your personal
            information with Etsy to monitor and analyse the use of our Service,
            to contact You, and to resolve any disputes.
          </li>
          <li className="mb-2">
            <b>For business transfers:</b> We may share or transfer Your
            personal information in connection with, or during negotiations of,
            any merger, sale of Company assets, financing, or acquisition of all
            or a portion of Our business to another company.
          </li>
          <li className="mb-2">
            <b>With other users: </b> when You share personal information or
            otherwise interact in the public areas with other users, such
            information may be viewed by all users and may be publicly
            distributed outside.
          </li>
        </ul>

        <h3 className="mb-2 font-bold">Retention of Your Personal Data</h3>
        <p className="mb-2">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations {'('}for example, if we are required to
          retain your data to comply with applicable laws{')'}, resolve
          disputes, and enforce our legal agreements and policies. This must not
          exceed more than 30 days.
        </p>
        <p className="mb-2">
          The 30 day count starts on the &quot;Event Date&quot; of the Event
          provided by You or the Event organiser. For example, if the event date
          is 2024-April-04, all data will be deleted on 2024-May-04 from the
          Company database.
        </p>
        <p className="mb-2">
          Please check{' '}
          <a href="https://www.etsy.com/legal/privacy/">
            Etsy&apos;s privacy policy
          </a>
          to learn more about how Etsy handles Your information.
        </p>

        <h3 className="mb-2 font-bold">Transfer of Your Personal Data</h3>
        <p className="mb-2">
          Your information, including Personal Data, is processed at the
          Company&apos;s operating offices and in any other places where the
          parties involved in the processing are located. It means that this
          information may be transferred to — and maintained on — computers
          located outside of Your state, province, country or other governmental
          jurisdiction where the data protection laws may differ than those from
          Your jurisdiction.
        </p>
        <p className="mb-2">
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </p>
        <p className="mb-2">
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </p>

        <h3 className="mb-2 font-bold">Delete Your Personal Data</h3>
        <p className="mb-2">
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You. Please note that We
          may ask You to verify Your identity before responding to such
          requests.
        </p>
        <p className="mb-2">
          Our Service may give You the ability to delete certain information
          about You from within the Service.
        </p>
        <p className="mb-2">
          You may update, amend, or delete Your information at any time by
          contacting us at <b>inviami.invites@gmail.com</b>. You may also
          contact Us to request access to, correct, or delete any personal
          information that You have provided to Us.
        </p>
        <p className="mb-2">
          Please note, however, that We may need to retain certain information
          when we have a legal obligation or lawful basis to do so.
        </p>

        <h3 className="mb-2 font-bold text-lg">
          Disclosure of Your Personal Data
        </h3>
        <h4 className="mb-2 font-bold">Business Transactions</h4>
        <p className="mb-2">
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.{' '}
        </p>
        <h4 className="mb-2 font-bold">Law enforcement</h4>
        <p className="mb-2">
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities {'('}e.g. a court or a government
          agency
          {')'}.
        </p>
        <h4 className="mb-2 font-bold">Other legal requirements</h4>
        <p className="mb-2">
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:{' '}
        </p>
        <ul className="mb-2 list-inside list-disc">
          <li className="mb-2">Comply with a legal obligation</li>
          <li className="mb-2">
            Protect and defend the rights or property of the Company
          </li>
          <li className="mb-2">
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li className="mb-2">
            Protect the personal safety of Users of the Service or the public
          </li>
          <li className="mb-2">Protect against legal liability</li>
        </ul>
        <h3 className="mb-2 font-bold">Security of Your Personal Data</h3>
        <p className="mb-2">
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.{' '}
        </p>

        <h3 className="mb-2 font-bold">Children&apos;s Privacy</h3>
        <p className="mb-2">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.{' '}
        </p>
        <p className="mb-2">
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent&apos;s consent before We collect and use that
          information.
        </p>
        <h3 className="mb-2 font-bold">Links to Other Websites</h3>
        <p className="mb-2">
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party&apos;s site. We strongly advise You to review the
          Privacy Policy of every site You visit.
        </p>
        <p className="mb-2">
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <h3 className="mb-2 font-bold">Changes to this Privacy Policy</h3>
        <p className="mb-2">
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p className="mb-2">
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the &quot;
          Last updated&quot; date at the top of this Privacy Policy.
        </p>
        <p className="mb-2">
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <h3 className="mb-2 font-bold">Contact Us</h3>
        <p className="mb-2">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul className="mb-2 list-inside list-disc">
          <li className="mb-2">
            By email: <b>inviami.invites@gmail.com</b>
          </li>
          <li className="mb-2">
            By post: <b>339 Hendon Way, NW4 3NB, London UK</b>
          </li>
        </ul>
      </section>
    </>
  );
};

export default Privacy;
